version: '3'

services:
  api:
    build: .
    image: strapi/strapi
    environment:
      - APP_NAME=strapi-app
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=mongo_db
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=example
      - DATABASE_SSL=false
      - DATABASE_AUTHENTICATION_DATABASE=admin
      - HOST=localhost
    ports:
      - 1337:1337
    volumes:
      - ./strapi-app:/usr/src/api/strapi-app
    depends_on:
      - mongo_db
    restart: always

  mongo_db:
    image: mongo
    environment:
        #- MONGO_INITDB_DATABASE=strapi
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
        - 27017
    volumes:
      - ./db:/data/db
    restart: always

  mongo-express:
     image: mongo-express
     restart: always
     ports:
       - 8081:8081
     environment:
       - ME_CONFIG_MONGODB_ADMINUSERNAME=root
       - ME_CONFIG_MONGODB_ADMINPASSWORD=example
       - ME_CONFIG_MONGODB_SERVER=mongo_db
